### ISSUE TITLE
About dataset Pix3D

### ISSUE THREAD

**Issue by David-655** [zxhuang1698/ShapeClipper#2]
Thank you very much for your work! I'm very interested in this work.
Could you tell us how to get the processed dateset Pix3D?
I saw the raw dataset contains three subfolders: img mask and model, but in your dataset has 7 subfolders.

**Comment by zxhuang1698** [comment]
Hi, thanks for your interest in our work. The depth and normal are obtained using pretrained omnidata (https://github.com/EPFL-VILAB/omnidata) and the pointclouds are sampled from the virtually scanned surfaces of the meshes. For pre-computed CLIP annotation, please check out CLIP_anno.py.

**Comment by David-655** [comment]
Thanks for your reply! Have a good weekend.
